# Generated by Django 4.0 on 2022-01-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_rename_sel_name_invoice_b_name_remove_order_gst_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
