# Generated by Django 4.0 on 2022-01-12 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_alter_order_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='num',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
