# Generated by Django 4.0 on 2022-01-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_order_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='b_address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='b_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='b_phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='s_address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='s_phone',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
