# Generated by Django 4.0 on 2022-01-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_alter_invoice_b_address_alter_invoice_b_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delete_it',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
