# Generated by Django 4.0 on 2022-01-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0009_alter_invoice_total_alter_order_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='render_total',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='render_amount',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='render_price',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
